//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeytur2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPassanger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPassanger()
        {
            this.TBLTrip_Info = new HashSet<TBLTrip_Info>();
        }
    
        public int Id { get; set; }
        public string adSoyad { get; set; }
        public string telNo { get; set; }
        public string tcNo { get; set; }
        public string cinsiyet { get; set; }
        public Nullable<int> odenenUcret { get; set; }
        public int payment_id { get; set; }
    
        public virtual TBLPayment TBLPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTrip_Info> TBLTrip_Info { get; set; }
    }
}
