//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeytur2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPayment()
        {
            this.TBLPassanger = new HashSet<TBLPassanger>();
        }
    
        public int id { get; set; }
        public string kartIsim { get; set; }
        public string kartNo { get; set; }
        public string skt { get; set; }
        public string cvv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPassanger> TBLPassanger { get; set; }
    }
}
