//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeytur2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTrip_Info
    {
        public int Id { get; set; }
        public string kalkıs { get; set; }
        public string inis { get; set; }
        public string tarih { get; set; }
        public string saat { get; set; }
        public int kapıNo { get; set; }
        public Nullable<int> koltukNo { get; set; }
        public int pass_id { get; set; }
    
        public virtual TBLPassanger TBLPassanger { get; set; }
    }
}
