//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeytur2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zeyturEntities : DbContext
    {
        public zeyturEntities()
            : base("name=zeyturEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLLoginScreen> TBLLoginScreen { get; set; }
        public virtual DbSet<TBLPassanger> TBLPassanger { get; set; }
        public virtual DbSet<TBLPayment> TBLPayment { get; set; }
        public virtual DbSet<TBLTrip_Info> TBLTrip_Info { get; set; }
    }
}
