//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zeytur2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLoginScreen
    {
        public int Id { get; set; }
        public string rol { get; set; }
        public string adSoyad { get; set; }
        public string sifre { get; set; }
    }
}
